name: Set up directory structure
description: Sets up the 0repo directory structure

runs:
  using: composite
  steps:
    - name: Clone feeds
      uses: actions/checkout@v4
      with:
        path: feeds
        fetch-depth: 0
        show-progress: false
    - name: Clone public
      uses: actions/checkout@v3
      with:
        path: public
        ref: gh-pages
    - name: Create directories & symlinks, config Git
      shell: bash
      run: |
        mkdir incoming
        ln -s feeds/0repo-config.py .
        ln -s public/archives.db .
        git config --global user.name apps.0install.net
        git config --global user.email webmaster@0install.net
