# Merge an incoming feed into the repository
name: Incoming
on:
  workflow_dispatch:
    inputs:
      feed_url:
        required: true
        description: URL of feed to merge in

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directory structure
        uses: 0install/apps/.github/actions/setup@master
      - name: Download feed
        run: curl -sSfL ${{inputs.feed_url}} -o incoming/feed.xml
      - name: Run 0repo
        uses: 0install/apps/.github/actions/0repo@master
        with:
          gpg_key: ${{secrets.GPG_KEY}}
      - name: Push feeds
        run: cd feeds; git push
