# Merge an incoming feed into the repository
name: Incoming
on:
  workflow_dispatch:
    inputs:
      feed_url:
        required: true
        description: URL of feed to merge in
      archive_url:
        required: false
        description: URL of archive to add to archives.db
concurrency:
  group: publish

jobs:
  incoming:
    runs-on: ubuntu-latest
    steps:
      - uses: 0install/github-actions/0repo-setup@v1
        with:
          git-user-name: apps.0install.net
          git-user-email: webmaster@0install.net
      - uses: 0install/github-actions/0repo@v1
        with:
          gpg-key: ${{secrets.GPG_KEY}}
          incoming-feed-url: ${{inputs.feed_url}}
          incoming-archive-url: ${{inputs.archive_url}}
      - name: Publish to GitHub Pages
        if: inputs.archive_url
        run: cd public; git push
      - name: Push modified feeds
        run: cd feeds; git push
