# Generate signed feeds and publish to GitHub Pages
name: Publish
on:
  workflow_dispatch: {}
  push:
    branches: [master]
    paths: ['0repo-config.py', '**/*.xml']
concurrency:
  group: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: 0install/github-actions/0repo-setup@v1
        with:
          git-user-name: apps.0install.net
          git-user-email: webmaster@0install.net
      - uses: 0install/github-actions/0repo@v1
        with:
          gpg-key: ${{secrets.GPG_KEY}}
      - name: Publish to GitHub Pages
        run: cd public; git push
