# Verify feeds in Pull Requests are valid
name: Verify
on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone feeds
        uses: actions/checkout@v2
        with:
          path: feeds
      - name: Clone public
        uses: actions/checkout@v2
        with:
          path: public
          ref: gh-pages
      - name: Set up repo
        run: |
          cp feeds/0repo-config.py .
          cp public/archives.db .
          mkdir incoming
      - name: Run 0repo
        env: {'NO_SIGN': '1'}
        run: ./feeds/0install.sh run http://0install.net/tools/0repo.xml
