# Verify feeds in Pull Requests are valid
name: Verify
on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directory structure
        uses: 0install/apps/.github/actions/setup@master
      - name: Run 0repo
        uses: 0install/apps/.github/actions/0repo@master
