# Verify feeds in Pull Requests are valid
name: Verify
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone feeds
        uses: actions/checkout@v2
        with:
          path: feeds
      - name: Clone public
        uses: actions/checkout@v2
        with:
          path: public
          ref: gh-pages
      - uses: 0install/0repo-action@master
        env: {'NO_SIGN': '1'}
